services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: next-app
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true # ローカルのコンテナ内でホットリロードを実行するため
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    tty: true
    stdin_open: true
